#! /bin/sh

set -e

# TODO @latest version spec (by default) + @dev-repo
# TODO install from git url or tarball (use --just-file project.opam?)
# TODO log all actions in file, show less to user by default
# TODO track installed versions
# TODO upgrade only if needed (currently will happily reinstall same version)
# TODO automatic opam update?

SWITCH_NAME="switch"

DATA_DIR="${XDG_DATA_HOME:-$HOME}/opamx"
mkdir -p "$DATA_DIR"
export OPAMROOT="${XDG_DATA_HOME:-$HOME/.local/share}/opamroot"

if [ ! -d "$OPAMROOT" ]; then
  opam init --bare --no-setup
  opam switch create --empty "$SWITCH_NAME"
fi
mkdir -p "$DATA_DIR/install"

help() {
  echo "Installer for ocaml programs via opam"
  echo
  echo "1. Add \$(opamx where) to your \$PATH"
  echo "2. Available commands :"
  echo "  opamx install [package]* # install given packages (upgrade all installed if no packages given)"
  echo "  opamx remove {package}+  # remove given packages"
  echo "  opamx update             # update available packages information"
  echo "  opamx where              # location where binaries are installed"
  echo "  opamx list               # list installed packages"
  echo "  opamx search ...         # search opam repository"
  exit 0
}

[ $# -gt 0 ] || help

cmd="$1"
shift

case "$cmd" in
"install")
  if [ $# -eq 0 ] && [ -n "$(opamx list)" ]; then
    opamx install $(opamx list)
  else
    # remove previously installed roots so that install will try to do less work
    opam remove $(opam list --roots -s) >> "$DATA_DIR/.log"
    opam install -y --destdir="$DATA_DIR" "$@"
    for i in "$@"; do
      cp "$OPAMROOT/$SWITCH_NAME/.opam-switch/install/$i.install" "$DATA_DIR/install/"
    done
  fi
  ;;
"remove")
  for i in "$@"; do
    opam-installer --prefix "$DATA_DIR" --remove "$DATA_DIR/install/$i.install" || true
    rm -f "$DATA_DIR/install/$i.install"
  done
  ;;
"list")
  ls -1 "$DATA_DIR/install" | sed 's/\.install$//'
  ;;
"update")
  opam update
  ;;
"search")
  opam search --no-switch "$@"
  ;;
"where")
  printf "%s\n" "$DATA_DIR/bin"
  ;;
*)
  help
  ;;
esac
